[services.web]
root = "web"
buildCommand = "npm run build"
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100

[services.service]
root = "service"
buildCommand = "go build -o main ."
startCommand = "./main"
healthcheckTimeout = 100
