[[services]]
name = "web"
root = "web"
buildCommand = "npm run build"
startCommand = "npm run start"

[[services]]
name = "service"
root = "service"
buildCommand = "go build -o out ."
startCommand = "./out"

[default]
service = "web"
